name: Merge

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag set to deploy; e.g. PR number or prod"
        type: string
        required: true
        default: 'test'

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  vars:
    name: Set Variables
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        if: ${{ ! inputs.tag }}
        id: pr
        uses: bcgov-nr/action-get-pr@v0.0.1

      - name: Set Tag
        id: tag
        run: echo "tag=${{ inputs.tag || steps.pr.outputs.pr }}" >> $GITHUB_OUTPUT

  # https://github.com/bcgov/quickstart-openshift-helpers
#  deploy-clab-test:
#    name: Deploy (test, tag=${{ needs.vars.outputs.tag }})
#    needs: [vars]
#    uses: ./.github/workflows/clab-test.yml
#    secrets: inherit
#    with:
#      tag: ${{ needs.vars.outputs.tag }}
 
  promote-test:
    name: Promote Images
    needs: [vars]
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [ frontend ]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.vars.outputs.tag }}
          tags: test
  
